### ISSUE TITLE
ArrayIndexOutOfBoundsException in regular expression

### ISSUE THREAD

**Issue by lopex** [jruby/joni#15]
source:
http://stackoverflow.com/questions/28703208/strange-exception-with-java8-nashorn-regex-engine
jdk nashorn bug:
https://bugs.openjdk.java.net/browse/JDK-8073818

**Comment by hns** [comment]
@lopex thanks for fixing this!

**Comment by hns** [comment]
This fixes the exception, but at least for JavaScript the result of the match is still not correct. 

A capture group that may be empty followed by a quantifier will always contain an empty string if the quantifier allows it. For instance, the following will return ["foo", ""] instead of ["foo", "foo"]:

/(.*)+/.exec("foo")

I'm not sure about Ruby, but this is incorrect in JavaScript. (java.util.regex also returns empty string for the capture group, so it may be correct behaviour for some languages.) 

With that said, here's a patch that I think might work for Nashorn:

https://gist.github.com/hns/c0c7284a8bb296246df4

Note that I replaced `stack[e.getMemStart()].getMemPStr()` with `e.getMemPStr()` because e is already the MEM_START stack entry. Also, I changed for the `endp != s` check, returning 0, and set isNull to -1 *otherwise*. 

Generally speaking I'm actually not sure why we need to check the capture group if the whole search did not advance. Joni is still a big mystery to me, so I may be missing something. Please let me know if what I'm saying makes sense.
