### ISSUE TITLE
Failed to parse textmate regex: invalid pattern in look-behind

### ISSUE THREAD

**Issue by KUGDev** [jruby/joni#77]
There is a pattern to match a string from 0 to 71 chars long: `(?<=^.{0,71})`.
I use it in a lot of cases in different places.
As I discovered, there is no functionality for handling lookbehind/lookahead together with the `{min,max}` quantifier.
Is there any workaround/planned development for this? Thank you

**Comment by enebo** [comment]
joni is a port of oniguruma and neither support lookbehind with non-fixed width quantifiers.  I think this might not be a common feature.  If I look over at regex101.com the description for postive look-behind is:

```text
(?<=...)
Ensures that the given pattern will match, ending at the current position in the expression. The pattern must have a fixed width. Does not consume any characters.
```

It does not say this about lookahead but neither engine supports that either. 

We never say never but there are no plans for either atm.

**Comment by enebo** [comment]
@KUGDev yeah.  I didn't realize until your comment that the key on lower right side is specific to the engine (I had used PCRE2).

Good luck with finding a workaround

**Comment by VitGottwald** [comment]
Hello @enebo. Actually oniguruma supports variable (finite) look aheads and lookbehind since [6.9.5](https://github.com/kkos/oniguruma/issues/237#issuecomment-855532427) which was released in April 2020.

I created a small playground with oniguruma 6.9.5 compiled to wasm with a thin JS wrapper. You can see an example of variable length look behind [here](https://6ppgn9.csb.app/?regex=A%28%3F%3C%3D%5E.%7B1%2C4%7D%29&text=123A).

```
Oniguruma Regex: A(?<=^.{1,4})
Text to scan: 123A
Result: {"index":0,"captureIndices":[{"start":3,"end":4,"length":1}]}
```

You can play with it by changing the text to `1234A` which will give the result as `null` because the lookbehind will no longer match the 1-4 characters specified via `^.{1,4}` (the match after `A` is now on position `5`).

**Comment by enebo** [comment]
@VitGottwald Interesting.  We need to look at what we are missing.   It is possible it isn't missing (need to figure this out) but that it is profiled off.  Ruby (which was why we ported originally still does not support this even though apparently it is in oniguruma).  Our port is also based off the fork Ruby has made of oniguruma so it is also possible they didn't pick this up (which seems unlikely).  Questions to be answered but thanks for bringing this to our attention.

**Comment by enebo** [comment]
@VitGottwald I have not looked personally but I did ask someone about this and Ruby had forked oniguruma to a project named onigmo and we based our port of onigmo.  Those two projects diverged at some point and it sounds like they might be resolving (but it is unclear).  This does explain why our last updates do not contain things that were introduced into oniguruma since onigmo has stopped picking them up.

I was not involved in any of this and I had forgotten the history of how this project came to be.

If you want to figure out what it takes to add this we are open to adding it. joni has profiles and while we don't need it for Ruby (yet anyways) we should be able to add it without affecting any other engine profiles which don't support support this.

**Comment by VitGottwald** [comment]
Thank you for the quick reply @enebo . We will start with the workaround first and then take a look if we could also contribute this feature to joni.

I looked for contributing.md or something like that but not did not find it. Is it OK to go ahead and open a draft PR for review if we figure out a way to implement this. Or do you want us to do some additional steps before that?

**Comment by enebo** [comment]
@VitGottwald that is fine.  If it is your first PR then someone will approve it so CI runs but then just let us know when it is beyond WIP status.
